apiVersion: v1
kind: Service
metadata:
  name: tokens
spec:
  selector:
    app: tokens
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokens
  template:
    metadata:
      labels:
        app: tokens
    spec:
      containers:
        - name: tokens
          image: jordanegs/tokens:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: URI_DB
              value: "mongodb://mongo:27017/tokenizacion_culqi?authSource=admin"
            - name: JWT_SECRET
              value: "123456"
            - name: JET_EXPIRED
              value: "60s"
          imagePullPolicy: Always
